INSERT INTO usuarios(Id_usuario, Email_usuario, Senha_usuario, Nome_usuario, Tipo_usuario) VALUE (2, "teste@gmail", "123", "teste", "Usuario");
INSERT INTO usuarios(Id_usuario, Email_usuario, Senha_usuario, Nome_usuario, Tipo_usuario) VALUE (1, "admin@gmail", "123", "admin", "Administrador");
INSERT INTO usuarios(Id_usuario, Email_usuario, Senha_usuario, Nome_usuario, Tipo_usuario) VALUE (3, "gestor@gmail", "123", "gestor", "Gestor");



INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (1, 2, NULL, '2026-06-11', NULL, -23.4620, -46.5330, false, NULL, true, NULL, true, 'Buraco profundo próximo ao cruzamento, oferecendo risco aos veículos e pedestres.', NULL, 'Pendente', 'Via', 'Registro', 'Buraco na Avenida Tiradentes', 'Dificulta', 'Dificulta', NULL);
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (2, 2, NULL, '2026-06-12', NULL, -23.4700, -46.5200, false, NULL, false, NULL, false, 'Infiltração identificada durante vistoria em prédio público municipal.', 'Parcial', 'Pendente', 'Prédio', 'Registro', 'Infiltração em prédio público', NULL, NULL, NULL);
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (3, 11, NULL, '2026-06-13', '2026-06-14', -23.4560, -46.5400, true, NULL, false, NULL, false, 'Entulho acumulado na calçada após descarte irregular, já removido pela equipe responsável.', NULL, 'Resolvido', 'Via', 'Registro', 'Entulho em calçada', 'Impede', 'NaoImpede', NULL);
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (4, 11, NULL, '2026-06-14', NULL, -23.4480, -46.5480, false, NULL, false, NULL, false, 'Semáforo intermitente causando lentidão no tráfego local.', NULL, 'Pendente', 'Via', 'Registro', 'Semáforo com defeito', 'NaoImpede', 'Dificulta', NULL);
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (5, 30, '2026-06-10', '2026-06-09', NULL, -23.4520, -46.5300, true, 3, true, '2026-07-05', true, 'Recapeamento de trecho com desgaste avançado no pavimento.', NULL, 'Em andamento', 'Via', 'Obra', 'Recapeamento da Rua São Jorge', 'Dificulta', 'Dificulta', 'Gestor responsável');
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (6, 31, '2026-06-16', '2026-06-12', NULL, -23.4660, -46.5240, false, 3, false, '2026-07-20', false, 'Manutenção programada em unidade pública com funcionamento parcial durante a obra.', 'Parcial', 'Planejado', 'Prédio', 'Obra', 'Manutenção em escola municipal', NULL, NULL, 'Gestor responsável');
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (7, 3, '2026-06-01', '2026-06-01', '2026-06-13', -23.4590, -46.5360, false, 3, false, '2026-06-13', false, 'Reparo em calçada concluído e liberado para circulação.', NULL, 'Concluído', 'Via', 'Obra', 'Reparo de calçada acessível', 'NaoImpede', 'NaoImpede', 'Gestor responsável');
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (8, 32, '2026-06-08', '2026-06-07', NULL, -23.4750, -46.5150, false, 100, false, '2026-06-28', false, 'Serviço de drenagem em andamento com interdição temporária da via.', NULL, 'Em pausa', 'Via', 'Obra', 'Drenagem pluvial no bairro', 'Impede', 'Impede', 'Equipe de obras');
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (9, 35, '2026-06-05', '2026-06-05', '2026-06-14', -23.3960, -46.4370, false, 3, false, '2026-06-14', false, 'Substituição de pavimentação concluída recentemente.', NULL, 'Concluído', 'Via', 'Obra', 'Pavimentação - Jardim Fortaleza', 'NaoImpede', 'NaoImpede', 'Gestor responsável');

INSERT INTO registros(id_registro, id_criador, data_inicio, data_registro, data_conclusao, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel)VALUES(10, 40, '2026-05-20', '2026-05-20', '2026-06-01', -23.5180, -46.3720, false, 3, false, '2026-06-01', false, 'Obra utilizada para demonstrar ocultação automática após 7 dias da conclusão.', NULL, 'Concluído', 'Via', 'Obra', 'Obra em andamento - Cabuçu', 'NaoImpede', 'NaoImpede', 'Gestor responsável');