INSERT INTO usuarios(Id_usuario, Email_usuario, Senha_usuario, Nome_usuario, Tipo_usuario) VALUE (2, "teste@gmail", "123", "teste", "Usuario");
INSERT INTO usuarios(Id_usuario, Email_usuario, Senha_usuario, Nome_usuario, Tipo_usuario) VALUE (1, "admin@gmail", "123", "admin", "Administrador");
INSERT INTO usuarios(Id_usuario, Email_usuario, Senha_usuario, Nome_usuario, Tipo_usuario) VALUE (3, "gestor@gmail", "123", "gestor", "Gestor");


INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov) VALUES (1, 100, '2026-05-03', '2026-05-03', -23.4543, -23.4543, false, NULL, true, '2026-05-20', true, 'Interdição parcial da via para manutenção', Null, 'Em andamento', 'Rua', 'Manutenção', 'Obra na avenida central', 'Impede', 'Dificulta');

INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (2, 100, NULL, '2026-06-06', -23.4620, -46.5330, false, NULL, true, NULL, true, 'Teste para validar exibição geral', NULL, 'Pendente', 'Via', 'Registro', 'Teste', 'Impede', 'NaoImpede', NULL);
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (3, 100, '2026-06-01', '2026-06-06', -23.4480, -46.5480, true, 100, false, '2026-07-02', false, 'Recapeamento e manutenção da via', NULL, 'Em andamento', 'Via', 'Obra', 'Recapeamento da rua', 'NaoImpede', 'Dificulta','sabesb');
INSERT INTO registros (id_registro, id_criador, data_inicio, data_registro, latitude, longitude, entulho, id_responsavel, poeira_excessiva, previsao, ruido_excessivo, descricao, funcionamento, status, tipo_local, tipo_registro, titulo, trafegop, trafegov, nome_responsavel) VALUES (4, 100, NULL, '2026-06-06', -23.4700, -46.5200, false, NULL, false, NULL, false, 'Problema identificado durante vistoria', 'Pleno', 'Pendente', 'Prédio', 'Registro', 'Inspeção do prédio', NULL, NULL, NULL);
